// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

namespace SpecData
{
    [GeneratorSpecDataResource]
    public static partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {115, 112, 69, 106, 46, 96, 70, 73, 89, 97, 112, 97, 73, 46, 125, 104};
    }
}
